Coverage:  Add `calculate_coverage` function.
open-contracting/kingfisher-colab pull request #55
Opened 2022-01-04 14:21 UTC by kindly

This is a pull requests for #35 

@duncandewhurst could you look over the documentation and have a go with the following colab sheet:

https://colab.research.google.com/drive/14B0uxBoyFRScCGb7xnBK_fNuKHjGZ_U4

It loads in some sample/random data that we use for testing kinglisher summaraize and contains most fields in the standard.  You could also use some other real data but you will have to import this branch using the pip install line in the first line in the notebook and import the calculate_coverage function.

2022-01-10 22:00 UTC, duncandewhurst requested changes
Thanks, @kindly!

I've pinged you some comments in the notebook and made some suggestions for the documentation.

2022-02-07 21:31 UTC, duncandewhurst commented on ocdskingfishercolab/__init__.py
> +    the total rows in this table will be the denomitor of the coverage percentage.
@kindly what do you think?

2022-02-07 22:30 UTC, duncandewhurst requested changes
Thanks @kindly I've suggested docs updates to reflect the new notation/logic and to improve the flow. There's one comment outstanding from my previous review: https://github.com/open-contracting/kingfisher-colab/pull/55#discussion_r780867708

2022-02-07 22:30 UTC, duncandewhurst commented on ocdskingfishercolab/__init__.py
> +    e.g. for the above example you could set the `scope` table to `awards` and `fields` to `:value/amount`.
Update to reflect new notation/logic.

```suggestion
    `fields` is a list of fields to measure the coverage of, specified using JSON Pointer.
    
    To specify fields that are children of the scope table, you can use either an absolute pointer or a relative pointer prefixed with `:`, e.g. if `scope` is set to 'awards', then `awards/value/amount` and `:value/amount` refer to the same field. Coverage of such fields is measured against the number of rows in the `scope` table.
    
    To specify fields that are not children of the scope table, use an absolute path, e.g. `tender/procurementMethod`. Coverage of such fields is measured against the number of releases/records.
```

2022-02-07 22:30 UTC, duncandewhurst commented on ocdskingfishercolab/__init__.py
> +    set `scope` to `contracts` and `fields` to `[':value', ':awards/suppliers/id']`.
Simplify

```suggestion
    If `scope` is set to `awards`, specify fields on related contracts by prefixing the path with `:contracts/`, e.g. to measure how many awards have a value and a related contract with a period, set `scope` to `awards` and `fields` to `[':value', ':contracts/period']`. Similarly, if `scope` is set to `contracts`, specify fields on related awards by prefixing the path with `:awards/`.
```

2022-02-07 22:30 UTC, duncandewhurst commented on ocdskingfishercolab/__init__.py
> +    A total coverage percentage of all the fields co-occuring together is also calculated.
Remove as covered above.

```suggestion
```

2022-02-09 16:44 UTC, kindly commented on ocdskingfishercolab/__init__.py
> +    the total rows in this table will be the denomitor of the coverage percentage.
I have changed it to the table name.

2022-02-11 12:01 UTC, merged